authors/urls.py
from django.urls import path
from . import views

app_name = 'authors'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('register/create/', views.register_create, name='register_create'),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('dashboard/recipe/<int:id>/edit', views.RecipeEdit.as_view(), name='recipe_edit'),
    path('dashboard/recipe/create', views.RecipeCreate.as_view(), name='recipe_create'),
    path('dashboard/recipe/delete', views.RecipeDelete.as_view(), name='recipe_delete'),
]

projeto1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

recipes-project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('authors/', include('authors.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.RecipeHome.as_view(), name='index'),
    path('recipe/search/', views.RecipeSearch.as_view(), name='search'),
    path('recipe/category/<int:category_id>/', views.RecipeCategory.as_view(), name='category'),
    path('recipe/<int:pk>/', views.RecipeDetail.as_view(), name='recipe'),
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Category(models.Model):
    name = models.CharField('Categoria', max_length=65)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField('Título', max_length=65)
    description = models.CharField('Descrição', max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField('Tempo de preparo')
    preparation_time_unit = models.CharField('Tempo de preparo de unidade', max_length=65)
    servings = models.IntegerField('Porções')
    servings_unit = models.CharField('Unidade da porção', max_length=65)
    preparation_steps = models.TextField('Etapas de preparo')
    preparation_steps_is_html = models.BooleanField('HTML', default=False)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)
    is_published = models.BooleanField('Publicado', default=False)
    cover = models.ImageField('Imagem', upload_to='recipes/cover/%Y/%m/%d/', blank=True, default='')
    category = models.ForeignKey(
        Category, verbose_name='Categoria', on_delete=models.SET_NULL, null=True, blank=True, default=None
    )
    author = models.ForeignKey(User, verbose_name='Usuário', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('recipes:recipe', args=(self.id,))

authors/forms/recipe_form.py
from django import forms
from django.core.exceptions import ValidationError
from collections import defaultdict

from recipes.models import Recipe
from utils.django_forms import add_attr, add_placeholder
from utils.strings import is_positive


class AuthorsRecipeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self._my_errors = defaultdict(list) 

        add_attr(self.fields.get('preparation_steps'), 'class', 'span-2')
        add_placeholder(self.fields['title'], 'Título da receita')
        add_placeholder(self.fields['description'], 'Descrição da receita')
        add_placeholder(self.fields['preparation_steps'], 'Etapas de preparo da receita')

    class Meta:
        model = Recipe
        fields = ('title', 'description', 'preparation_time', 'preparation_time_unit',
                  'preparation_steps', 'servings', 'servings_unit', 'cover', 'category')

        widgets = {
            'cover': forms.FileInput(
                attrs={
                    'class': 'span-2',
                }
            ),
            'servings_unit': forms.Select(
                choices=(
                    ('Porções', 'Porções'),
                    ('Unidade', 'Unidades'),
                    ('Copos', 'Copos'),
                )
            ),
            'preparation_time_unit': forms.Select(
                choices={
                    ('Minutos', 'Minutos'),
                    ('Horas', 'Horas'),
                }
            ),
            'category': forms.Select(
                attrs={
                    'class': 'span-2',
                }
            ),
        }

        prepopulated_fields = {
        'slug': ('title',)
        }


    def clean(self, *args, **kwargs):
        super_clean = super().clean(*args, **kwargs)

        cleaned_data = self.cleaned_data
        title = cleaned_data.get('title')
        description = cleaned_data.get('description')
        preparation_steps = cleaned_data.get('preparation_steps')

        if len(title) < 5:
            self._my_errors['title'].append('O título deve ter mais de 5 caracteres!')

        if len(preparation_steps) < 10:
            self._my_errors['preparation_steps'].append('O preparo deve ter no mínimo 10 caracteres!')

        if description == title:
            self._my_errors['title'].append('O título deve ser diferente da descrição!')
            self._my_errors['description'].append('A descrição deve ser diferente do título!')

        if self._my_errors:
            raise ValidationError(self._my_errors)

        return super_clean


    def clean_preparation_time(self):
        field_name = 'preparation_time'
        preparation_time = self.cleaned_data.get(field_name)
        
        if not is_positive(preparation_time):
            self._my_errors[field_name].append('O tempo de preparo não pode ser negativo!')

        return preparation_time

    def clean_servings(self):
        field_name = 'servings'
        servings = self.cleaned_data.get(field_name)

        if not is_positive(servings):
            self._my_errors[field_name].append('O número de porções não pode ser negativo!')

        return servings

recipes/views.py
from django.http import Http404
from django.db.models import Q
from django.core.paginator import Paginator
from django.shortcuts import get_list_or_404, get_object_or_404
from django.views.generic import ListView, DetailView

from .models import Category, Recipe
from utils.pagination import make_pagination


import os


PER_PAGE = int(os.environ.get('PER_PAGE', 6))  # Used to set a maximum number of recipes in each page.


class RecipeListViewBase(ListView):
    model = Recipe
    context_object_name = 'recipes'
    paginate_by = None
    ordering = ['-id']
    template_name = 'recipes/pages/home.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            is_published=True
        )

        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        page_obj, pagination_range = make_pagination(
            self.request,
            ctx.get('recipes'),
            PER_PAGE,
        )
        ctx.update(
            {'recipes': page_obj, 'pagination_range': pagination_range}
        )

        return ctx


class RecipeHome(RecipeListViewBase):
    template_name = 'recipes/pages/home.html'


class RecipeDetail(DetailView):
    model = Recipe
    context_object_name = 'recipe'
    template_name = 'recipes/pages/recipe.html'

    def get_object(self, *args, **kwargs):
        obj = super().get_object(*args, **kwargs)
        pk = self.kwargs.get('pk')
        obj = get_object_or_404(Recipe, id=pk, is_published=True)

        return obj

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx.update(
            {
                'is_detail_page': True,
            }
        )

        return ctx


class RecipeCategory(RecipeListViewBase):
    template_name = 'recipes/pages/category.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        category_id = self.kwargs['category_id']
        qs = get_list_or_404(
            qs.filter(
                is_published=True,
                category__id=category_id,
            )
        )

        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        category_name = ctx.get('recipes')[0].category.name
        ctx.update(
            {'title': f'{category_name}'}
        )

        return ctx


class RecipeSearch(RecipeListViewBase):
    template_name = 'recipes/pages/search.html'

    def get_search_term(self):
        search_term = self.request.GET.get('q', '').strip()

        if not search_term:
            raise Http404

        return search_term

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        search_term = self.get_search_term()
        qs = qs.filter(
            Q(
                Q(title__icontains=search_term) |  # The pipe | is used like a "OR".
                Q(description__icontains=search_term)
            ),
            is_published=True,
        )

        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        search_term = self.get_search_term()
        ctx.update(
            {
                'page_title': f'Pesquisa por "{search_term}"',
                'aditional_url_query': f'&q={search_term}',
            }
        )

        return ctx

recipes/templates/recipes/partials/_head.html
{% load static %}


    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css" integrity="sha512-P9vJUXK+LyvAzj8otTOKzdfF1F3UYVl13+F8Fof8/2QNb8Twd6Vb+VD52I7+87tex9UXxnzPgWA3rH96RExA7A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/brands.min.css" integrity="sha512-sVSECYdnRMezwuq5uAjKQJEcu2wybeAPjU4VJQ9pCRcCY4pIpIw4YMHIOQ0CypfwHRvdSPbH++dA3O4Hihm/LQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/solid.min.css" integrity="sha512-tk4nGrLxft4l30r9ETuejLU0a3d7LwMzj0eXjzc16JQj+5U1IeVoCuGLObRDc3+eQMUcEQY1RIDPGvuA7SNQ2w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static '/recipes/css/styles.css' %}">

 

recipes/templates/recipes/partials/_recipe.html
<div class="recipe recipe-list-item">
    {% if recipe.cover %}
        <div class="recipe-cover">
            <a href="{% url 'recipes:recipe' recipe.id %}">
                <img src="{{ recipe.cover.url }}" alt="Temporario">
            </a>
        </div>
    {% endif %}

    <div class="recipe-title-container">
        <a href="{% url 'recipes:recipe' recipe.id %}">{{ recipe.title }}</a>
    </div>

        <div class="recipe-author">
            <span class="recipe-author-item">
                <i class="fas fa-user"></i>
                {% if recipe.author is not None %}      
                    {% if recipe.author.first_name %}
                        {{ recipe.author.first_name }} {{ recipe.author.last_name }}
                    {% else %}
                        {{ recipe.author.username }}
                    {% endif %}
                {% else %}
                    Desconhecido
                {% endif %}
            </span>

            <span class="recipe-author-item">
                <i class="fas fa-calendar-alt"></i>
                {{ recipe.created_at|date:"d/m/Y" }}
            </span>

            {% if recipe.category is not None %}
                <span class="recipe-author-item">
                    <a href="{% url 'recipes:category' recipe.category.id %}">
                        <i class="fas fa-layer-group"></i>
                        <span>{{ recipe.category.name }}</span>
                    </a>
                </span>
            {% endif %}

        </div>

        <div class="recipe-content description">
            <p>{{ recipe.description }}</p>
        </div>

        <div class="recipe-meta-container">
            <div class="recipe-meta recipe-preapration">
                <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i>Preparo</h3>
                <div class="recipe-meta-text">
                    {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
                </div>
            </div>

            <div class="recipe-meta recipe-servings">
                <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i>Porções</h3>
                <div class="recipe-meta-text">
                    {{ recipe.servings }} {{ recipe.servings_unit }}
                </div>
            </div>      
        </div>

        {% if is_detail_page is not True %}
            <footer class="recipe-footer">
                <a href="{% url 'recipes:recipe' recipe.id %}" class="recipe-read-more button button-dark button-full-width">
                    <i class="fas fa-eye"></i>
                    <span>Ver mais...</span>
                </a>
            </footer>
        {% endif %}

        {% if is_detail_page is True %}
            <div class="preparation-steps">
                {% if recipe.preparation_step_is_html is True %}
                    <span>{{ recipe.preparation_steps|safe }}</span>
                {% else %}
                    <span>{{ recipe.preparation_steps|linebreaksbr }}</span>               
                {% endif %}
            </div>
        {% endif %}

</div>